# Generated by Django 5.0.3 on 2024-03-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_produto_estoque_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='produto',
            new_name='produto_pk',
        ),
    ]
